version: '3.1'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./php/code:/code
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx

    
  php:
    image: php:7.1.10-fpm
    container_name: php
    volumes:
      - ./php/code:/code

