version: '3.1'

services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment: 
      - MYSQL_ROOT_PASSWORD=abbcccdddd
      - MYSQL_USER=1061dbproject
      - MYSQL_PASSWORD=room3506ITAC
      - MYSQL_DATABASE=TestProjectDB
    volumes:
      - ./maria_db/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
      - dbproject

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment: 
      - PMA_HOST=mariadb
      # for default login
      # - PMA_USER=root
      # - PMA_PASSWORD=abbcccdddd
    depends_on:
      - mariadb
    volumes:
      - ./phpmyadmin/sessions:/sessions
      - ./phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
      - ./phpmyadmin/theme:/www/themes/theme/
    ports:
      - 8080:80
    networks: 
      - dbproject

networks: 
  dbproject:
    driver: "bridge"