ftp:
  image: stilliard/pure-ftpd
  container_name: ftp
  volumes:
    - "./php/code:/home/ftpusers/1061dbproject"
    - "./pure-ftpd/user:/etc/pure-ftpd"
    - "./pure-ftpd/ssl:/etc/ssl/private/"
  ports:
    - "21:21"
    - "30000:30000"
    - "30001:30001"
    - "30002:30002"
    - "30003:30003"
    - "30004:30004"
    - "30005:30005"
    - "30006:30006"
    - "30007:30007"
    - "30008:30008"
    - "30009:30009"
  environment:
    PUBLICHOST: localhost
  networks: 
      - dbproject

# enter the container:
# pure-pw useradd code -u ftpuser -d /home/ftpusers/code
# pure-pw mkdb
