version: '3.1'

services:
    nginx:
        image: nginx
        container_name: webserver
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx.conf:/etc/nginx/conf.d"
            - "./static:/usr/share/nginx/html"
            # - "./ssl:/etc/nginx/ssl"
